name: Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json

    # Install backend dependencies
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci

    # Install frontend dependencies
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    # Install Playwright browsers
    - name: Install Playwright Browsers
      working-directory: ./frontend
      run: npx playwright install --with-deps

    # Build backend
    - name: Build backend
      working-directory: ./backend
      run: npm run build

    # Run backend tests (Jest)
    - name: Run backend unit tests
      working-directory: ./backend
      run: npm test

    # Run frontend tests (Jest)
    - name: Run frontend unit tests
      working-directory: ./frontend
      run: npm test -- --coverage --watchAll=false

    # Start backend in background
    - name: Start backend server
      working-directory: ./backend
      run: npm run dev &
      env:
        NODE_ENV: test

    # Wait for backend to be ready
    - name: Wait for backend
      run: |
        timeout 120 bash -c 'until curl -f http://localhost:5000/api/tasks; do echo "Waiting for backend..."; sleep 3; done'
        echo "Backend is ready!"

    # Start frontend in background
    - name: Start frontend server
      working-directory: ./frontend
      run: npm start &
      env:
        CI: true

    # Wait for frontend to be ready
    - name: Wait for frontend
      run: |
        timeout 180 bash -c 'until curl -f http://localhost:3000; do echo "Waiting for frontend..."; sleep 3; done'
        echo "Frontend is ready!"
        # Give it a few more seconds to fully initialize
        sleep 5

    # Run Playwright tests
    - name: Run Frontend E2E tests
      working-directory: ./frontend
      run: npx playwright test

    # Run Backend API tests
    - name: Run Backend E2E tests
      working-directory: ./backend
      run: npx playwright test

    # Upload Playwright reports
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-frontend
        path: frontend/playwright-report/
        retention-days: 30

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-backend
        path: backend/playwright-report/
        retention-days: 30

    # Upload test results
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          frontend/test-results/
          backend/test-results/
        retention-days: 30
